"""
TrustGate Flex — Alert routes
Security alerts generated by blocked access or high-risk activity.
"""

from __future__ import annotations

import logging
import traceback
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from backend.core.security import get_current_user, require_roles
from backend.db.database import get_db
from backend.models.models import Alert, User

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/alerts", tags=["alerts"])


# ====================================================================
#  GET /alerts
# ====================================================================
@router.get("")
def list_alerts(
    severity: Optional[str] = Query(None, description="Filter by CRITICAL, HIGH, etc."),
    skip: int = Query(0, ge=0),
    limit: int = Query(50, ge=1, le=100),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """List security alerts, optionally filtering by severity."""
    logger.info("→ [GET /alerts] called")
    try:
        query = db.query(Alert)
        if severity:
            query = query.filter(Alert.severity == severity.upper())

        rows = (
            query.order_by(Alert.sent_at.desc())
            .offset(skip)
            .limit(limit)
            .all()
        )

        return {
            "total": len(rows),
            "alerts": [
                {
                    "id": a.id,
                    "severity": a.severity,
                    "message": a.message,
                    "acknowledged": a.acknowledged,
                    "sent_at": a.sent_at.isoformat(),
                }
                for a in rows
            ],
        }
    except Exception as e:
        logger.exception("Exception in /alerts")
        return {"error": str(e), "step": "list_alerts execution", "traceback": traceback.format_exc()}


# ====================================================================
#  POST /alerts/{alert_id}/acknowledge
# ====================================================================
@router.post("/{alert_id}/acknowledge")
def acknowledge_alert(
    alert_id: str,
    user: User = Depends(require_roles("ADMIN")),
    db: Session = Depends(get_db),
):
    """Mark an alert as acknowledged."""
    logger.info(f"→ [POST /alerts/{alert_id}/acknowledge] called")
    try:
        alert = db.query(Alert).filter(Alert.id == alert_id).first()
        if not alert:
            raise HTTPException(status_code=404, detail="Alert not found")
        if alert.acknowledged:
            return {"status": "already acknowledged", "alert_id": alert.id}

        alert.acknowledged = True
        logger.info(f"→ Saving to DB: Alert {alert_id} acknowledged by {user.email}")
        db.commit()

        return {"status": "acknowledged", "alert_id": alert.id}
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Exception in /alerts/acknowledge")
        return {"error": str(e), "step": "acknowledge_alert execution", "traceback": traceback.format_exc()}
